linters:
  enable-all: true
  disable:
  - cyclop
  - gocognit
  - dogsled
  - errorlint
  - exhaustivestruct
  - exhaustruct
  - funlen
  - importas
  - interfacer
  - ireturn
  - gochecknoglobals
  - gochecknoinits
  - godot
  - maintidx
  - maligned
  - nlreturn
  - nosnakecase
  - paralleltest
  - prealloc
  - predeclared
  - scopelint
  - tagliatelle
  - varnamelen
  - wsl

  # Consider enabling
  - gocyclo
  - wrapcheck

  # Usually disabled but useful for checking everything has godoc
  - golint

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(moqueries.org/runtime)
  depguard:
    rules:
      main:
        list-mode: strict
        allow:
        - $gostd
        - moqueries.org/deephash
        - moqueries.org/runtime
  revive:
    rules:
    - name: var-naming
      disabled: true
  stylecheck:
    checks:
    - "all"
    - "-ST1000"
    - "-ST1003"
    initialisms:
    - "-ID"

issues:
  exclude-use-default: false
  exclude-rules:
  - path: '(.+)_test.go'
    linters:
    - forcetypeassert
    - goconst
    - gocritic
    - goerr113
    - nestif
  - path: 'testpkg'
    linters:
    - deadcode
    - revive
    - stylecheck
    - unused
  include:
  # disable excluding of issues about comments from golint.
  - EXC0002
